name: pypots-dev

channels:
    - conda-forge
    - pytorch
    - pyg
    - nodefaults

dependencies:
    ## basic
    #- conda-forge::python
    #- conda-forge::pip
    #- conda-forge::scipy
    #- conda-forge::numpy
    #- conda-forge::scikit-learn
    #- conda-forge::pandas <2.0.0
    #- conda-forge::h5py
    #- conda-forge::tensorboard
    #- conda-forge::pygrinder >=0.4
    #- conda-forge::tsdb >=0.2
    #- conda-forge::matplotlib
    #- pytorch::pytorch >=1.10.0
    ## Below we install the latest pypots because we need pypots-cli in it for development.
    ## PyPOTS itself already includes all basic dependencies.
    - conda-forge::pypots

    # optional
    - pyg::pyg
    - pyg::pytorch-scatter
    - pyg::pytorch-sparse

    # test
    - conda-forge::pytest-cov
    - conda-forge::pytest-xdist

    # doc
    - conda-forge::furo
    - conda-forge::sphinx
    - conda-forge::docutils
    - conda-forge::sphinxcontrib-bibtex
    - conda-forge::sphinx-autodoc-typehints

    # dev
    - conda-forge::black
    - conda-forge::flake8
    - conda-forge::pre-commit
    - conda-forge::jupyterlab

    - pip:
        # doc
        - sphinxcontrib-gtagjs
        # hyperparameter tuning
        - nni
